### ISSUE TITLE
(Suggestion) Flat rate instead of %

### ISSUE THREAD

**Issue by VanilaBOI** [33mamaster/LC-LifetimeCruiserWarranty#2]
Could you make a config option to have the penalty for leaving behind/destroying the cruiser be a set amount of credits and not a % of the current credits?

**Comment by 33mamaster** [comment]
Shouldn't be too hard. I'll look into it.

**Comment by 33mamaster** [comment]
Done. Also fixed a UI bug at the same time.
v1.3.0 uploaded to Thunderstore now. Should appear in mod loaders whenever they index.

**Comment by VanilaBOI** [comment]
Thanks a lot, this will really help in the balancing of my modpack.
